# Generated by Django 3.2.6 on 2021-09-12 23:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FriendsLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='博客网站名')),
                ('friend_url', models.CharField(max_length=100, verbose_name='博客URL')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='博客创建时间')),
            ],
            options={
                'verbose_name': '文章内容',
                'verbose_name_plural': '文章内容',
                'ordering': ['created'],
            },
        ),
    ]
