# Generated by Django 3.2.6 on 2021-09-14 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_friendslink'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.TextField(default='xingming是行茗的个人技术博客', help_text='用来作为SEO中description,长度参考SEO标准', max_length=240, verbose_name='描述'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='description',
            field=models.TextField(default='xingming 是 Django+Bootstrap4 搭建的个人博客类型网站', help_text='用来作为SEO中description,长度参考SEO标准', max_length=240, verbose_name='描述'),
        ),
    ]
